import { Skill } from "dev-portfolio";
import { SkillWrapper, TeckStackWrap } from "./style";

export const Techstack = () => {
  return (
    <TeckStackWrap id="['SKILL', 'akar-icons:stack-overflow-fill']">
      <h3>Skill</h3>
      <SkillWrapper>
        <Skill
          title="Javascript"
          titleSize="16px"
          iconName="ion:logo-javascript"
          iconSize="40px"
          iconColor="#F0DB4F"
        />
        <Skill
          title="Typescript"
          titleSize="16px"
          iconName="logos:typescript-icon"
          iconSize="35px"
        />
        <Skill
          title="React"
          titleSize="16px"
          iconName="logos:react"
          iconSize="35px"
        />
        <Skill
          title="Next.js"
          titleSize="16px"
          iconName="devicon:nextjs"
          iconSize="35px"
        />
        <Skill
          title="Recoil"
          titleSize="16px"
          iconName="logos:recoil"
          iconSize="32px"
        />
        <Skill
          title="Zustand"
          titleSize="16px"
          iconName="fluent-emoji-flat:bear"
          iconSize="40px"
        />
        <Skill
          title="HTML"
          titleSize="16px"
          iconName="vscode-icons:file-type-html"
          iconSize="40px"
        />
        <Skill
          title="CSS"
          titleSize="16px"
          iconName="vscode-icons:file-type-css"
          iconSize="40px"
        />
        <Skill
          title="Scss"
          titleSize="16px"
          iconName="vscode-icons:file-type-scss2"
          iconSize="40px"
        />
        <Skill
          title="Style-Component"
          titleSize="16px"
          iconName="vscode-icons:file-type-styled"
          iconSize="40px"
        />
        <Skill
          title="Emotion"
          titleSize="16px"
          iconName="skill-icons:emotion-light"
          iconSize="40px"
        />
        <Skill
          title="Storybook"
          titleSize="16px"
          iconName="vscode-icons:file-type-storybook"
          iconSize="40px"
        />
        <Skill
          title="Vanilla-Extract"
          titleSize="16px"
          iconName="vscode-icons:file-type-vanilla-extract"
          iconSize="40px"
        />
        <Skill
          title="npm"
          titleSize="16px"
          iconName="logos:npm-icon"
          iconSize="32px"
        />
        <Skill
          title="github-action"
          titleSize="16px"
          iconName="logos:github-actions"
          iconSize="35px"
        />
      </SkillWrapper>
    </TeckStackWrap>
  );
};
